classes = {	0: "Speed Limit 20",
            1: "Speed Limit 30",
            2: "Speed Limit 50",
            3: "Speed Limit 60",
            4: "Speed Limit 70",
            5: "Speed Limit 80",
            6: "End of Speed Limit 80",
            7: "Speed Limit 100",
            8: "Speed Limit 120",
            9: "No Passing",
            10: "No Passing for Vehicles over 3.5 metric tons",
            11: "Right-of-way at the next intersection",
            12: "Priority Road",
            13: "Yield",
            14: "Stop",
            15: "No Vehicles",
            16: "Vehicles over 3.5 metric tons prohibited",
            17: "No Entry",
            18: "General Caution",
            19: "Dangerous Curve to the right",
            20: "Dangerous Curve to the left",
            21: "Double Curve",
            22: "Bumpy Road",
            23: "Slippery Road",
            24: "Road Narrows on the right",
            25: "Road Work",
            26: "Traffic Signals",
            27: "Pedestrians",
            28: "Children Crossing",
            29: "Bicycles Crossing",
            30: "Beware Of Ice/Snow",
            31: "Wild Animals Crossing",
            32: "End of all speed and passing Limits",
            33: "Turn Right Ahead",
            34: "Turn Left Ahead",
            35: "Ahead Only",
            36: "Go Straight or right",
            37: "Go straight or left",
            38: "Keep right",
            39: "Keep left",
            40: "Roundabout mandatory",
            41: "End of No Passing",
            42: "End of No Passing by vehicles over 3.5 metric tons",
            }
